Introduce a logical plan rule to avoid wrapping RowNumber in AggregateFunction (#100)
Bytedance internal optimizer will generate plans that wrap `RowNumber`
in an `AggregateFunction`, it works in Spark, but doesn't work in
Rapdis, with following error.

```
java.lang.ClassCastException: com.nvidia.spark.rapids.window.GpuRowNumber$ cannot be cast to org.apache.spark.sql.rapids.aggregate.GpuAggregateFunction
	at com.nvidia.spark.rapids.GpuOverrides$$anon$104.convertToGpu(GpuOverrides.scala:2131)
	at com.nvidia.spark.rapids.GpuOverrides$$anon$104.convertToGpu(GpuOverrides.scala:2112)
	at com.nvidia.spark.rapids.window.GpuWindowExpressionMetaBase.$anonfun$convertToGpu$1(GpuWindowExpression.scala:193)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at com.nvidia.spark.rapids.window.GpuWindowExpressionMetaBase.convertToGpu(GpuWindowExpression.scala:193)
	at com.nvidia.spark.rapids.window.GpuWindowExpressionMetaBase.convertToGpu(GpuWindowExpression.scala:42)
	at com.nvidia.spark.rapids.UnaryExprMetaBase.convertToGpu(RapidsMeta.scala:1366)
	at com.nvidia.spark.rapids.UnaryExprMetaBase.convertToGpu(RapidsMeta.scala:1358)
	at com.nvidia.spark.rapids.window.GpuBaseWindowExecMeta.$anonfun$convertToGpu$2(GpuWindowExecMeta.scala:105)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at com.nvidia.spark.rapids.window.GpuBaseWindowExecMeta.convertToGpu(GpuWindowExecMeta.scala:105)
	at com.nvidia.spark.rapids.window.GpuBaseWindowExecMeta.convertToGpu(GpuWindowExecMeta.scala:37)
	at com.nvidia.spark.rapids.SparkPlanMeta.convertIfNeeded(RapidsMeta.scala:840)
	at com.nvidia.spark.rapids.GpuProjectExecMeta.convertToGpu(basicPhysicalOperators.scala:58)
	at com.nvidia.spark.rapids.GpuProjectExecMeta.convertToGpu(basicPhysicalOperators.scala:49)
	at com.nvidia.spark.rapids.SparkPlanMeta.convertIfNeeded(RapidsMeta.scala:840)
	at org.apache.spark.sql.rapids.execution.GpuShuffleMetaBase.convertToGpu(GpuShuffleExchangeExecBase.scala:124)
	at org.apache.spark.sql.rapids.execution.GpuShuffleMetaBase.convertToGpu(GpuShuffleExchangeExecBase.scala:46)
	at com.nvidia.spark.rapids.SparkPlanMeta.convertIfNeeded(RapidsMeta.scala:840)
	at com.nvidia.spark.rapids.SparkPlanMeta.$anonfun$convertToCpu$1(RapidsMeta.scala:655)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
```


This pr try to unwrap the useless `AggregateFunction` so that it can run
on Rapids